### ISSUE TITLE
[需求]求一个分享到印象笔记的扩展

### ISSUE THREAD

**Issue by AmintaCCCP** [cyanzhong/actions.taio.app#1]
类似PC端的马克飞象
印象笔记手机端不支持markdown, 想用taio作为入口

**Comment by cyanzhong** [comment]
印象笔记有接口么？

**Comment by AmintaCCCP** [comment]
> 印象笔记有接口么？

马克飞象,mweb,轻芒杂志之类的应用都可以同步。
看看这个是不是: https://dev.yinxiang.com/
能接入的话，手机端阅读写笔记剪藏能替掉一大批APP

**Comment by cyanzhong** [comment]
已经有计划做发布到各种平台的动作了，此 issue 先关闭，感谢反馈。
