### ISSUE TITLE
【需求】求一个能直接把md文档提交git的动作

### ISSUE THREAD

**Issue by hr1ycfl** [cyanzhong/actions.taio.app#5]
【需求】求一个能直接把md文档提交git的动作
如 [Working Copy](https://workingcopyapp.com/)

**Comment by cyanzhong** [comment]
为什么不用 Working Copy？

**Comment by hr1ycfl** [comment]
😅 因为working copy 的提交需要付费，而且还要来回切换应用。

**Comment by cyanzhong** [comment]
没有这种计划，完善地支持 Git 是非常复杂的事情。
