### ISSUE TITLE
how can I share a private action with other people without push to this repo?

### ISSUE THREAD

**Issue by billzhuang** [cyanzhong/actions.taio.app#6]
如题。谢谢。

**Comment by cyanzhong** [comment]
https://airtable.com/shrZtX5DaukiL4ZFt

**Comment by billzhuang** [comment]
但我想share一个私人的action，里面有我的serects之类，airtable这个表单我看介绍，还是会public出来的。我理解的对么？

**Comment by cyanzhong** [comment]
您好，分享这个的目的是？我似乎没太懂，似乎是又分享又不分享...

**Comment by billzhuang** [comment]
你好，我做了一个action，我只想分享给我认识的几个同事，不想别人找到和看到。

这个action里包含了一些app secrets之类。

**Comment by cyanzhong** [comment]
有几种方法，第一种是 AirDrop，同事接收到之后用 Taio 打开可以安装。

如果需要通过链接安装，将文件上传到一个服务器上，获得下载链接，然后通过 [URL Schemes](https://docs.taio.app/#/cn/integration/url-schemes?id=%e5%af%bc%e5%85%a5%e5%8a%a8%e4%bd%9c) 安装。
